version: '3'
services:
  mongodb:
    image : mongo
    restart: always
    ports:
      - "27016:27016"
    container_name: mongo-container
    network_mode: host

  MuzixTasks:
    image: spring-boot
    restart: always
    build:
      MuzixTasks/
    container_name: spring-docker
    network_mode: host
    ports:
      - 8085:8085
    expose:
      - 8085

  zuul:
    image: zuul
    restart: always
    build:
      zuul/
    container_name: zuul-container
    network_mode: host
    ports:
      - 8061:8061
    expose:
      - 8061


  Eurekaserver:
    image: eureka
    restart: always
    build:
      EurekaServer/
    container_name: eureka-container
    network_mode: host
    ports:
      - 8062:8062
    expose:
      - 8062

 

